Adding my thoughts on #8

diff --git a/modules/docker/docker b/modules/docker/docker
--- a/modules/docker/docker
+++ b/modules/docker/docker
@@ -122,10 +122,11 @@ docker() {
 		set +x
 	;;
 	up)
-		if isosx; then
-			boot2docker start
-			docker init
+		if ! isosx; then
+			echo "ERROR: Only available under OS X"
 		fi
+		boot2docker start
+		docker init
 	;;
 	upgrade)
 		if isosx; then
